name: Generate SHA Keys (Final Fix)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. إنشاء keystore
      - name: Create Debug Keystore
        run: |
          mkdir -p ~/.android
          mkdir -p ~/.config/.android

          keytool -genkeypair \
            -keystore ~/.android/debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android,O=Android,C=US"

          # 🔥 الحل الحقيقي
          cp ~/.android/debug.keystore ~/.config/.android/debug.keystore

      # 4. تشغيل Gradle
      - name: Generate SHA
        run: |
          cd android
          gradle signingReport